language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 'lts/*'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - verify
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: verify
      script: commitlint-travis
    - stage: test
      script: npm test
    - stage: deploy
      script: npm run semantic-release
